name: Publish Docker
on: 
  push:
    branches: 
      [master, 4-production]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: docker.pkg.github.com
          name:  docker.pkg.github.com/amsverchkov/api-nest/api-nest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}